# -*- coding: utf-8 -*-
#
# This file is part of xrootdpyfs
# Copyright (C) 2015 CERN.
#
# xrootdpyfs is free software; you can redistribute it and/or modify it under
# the terms of the Revised BSD License; see LICENSE file for more details.

#
# Tox configuration file
#

[tox]
envlist = {py27}-{lowest,latest,devel}

[testenv:release]
deps =
    twine >= 1.4.0
    wheel
    Sphinx
    sphinx-pypi-upload
commands =
    /bin/rm -Rf {toxinidir}/dist
    {envpython} setup.py clean --all
    {envpython} setup.py sdist bdist_wheel build_sphinx
    twine upload -r pypi {posargs} dist/*
    python setup.py upload_docs
